---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-hr-server-db-secret
  namespace: ai-services
spec:
  encryptedData:
    DSN: AgA5fMi18g48v7+ffpREEit9HjNFbVz1tWufCyBx8Hs5mvC3AiSe9TopCdgijj5jCdiFXDzW9wGqcoet0DK2rhXka2cUxg9fdWWdkZeJSy0nJmZ7wAI4q63sLxunk8wSCqV1fleb02ZYi1//7GIoyaC5gPAd+H//6lDxWeeqQrIDxN14T8l8BAwTfRLIQ6kElJUKCCtjkbtr4Sa62lVo5TXvNlbH+8tL8ndAZIuJlcw4OrNxHVjUcCWJhTdh2ltnLbvZavgeZxwF3dhmhdIuti3M2Wbp8JGIIiMBU36B7sOwyGc9SMlY4HGM4AsVSo5OwxnMJ3N5kpDQIc/ASQ8oFSglacWhAZJLOoLiXVutVmATLyqNMJZtnYuD+SnkrE4GU1hT1rAUFmS3k8wDWgL7e/Xq2NaolT/CiqeuG8svzBjSKzHKnzi5PEQrlp4+ySO51mLdTYJGQ1hd0TEAZoSek6KGh/lxCTPQUX6OfSGEXaCQ9zfh1zvdxUvdYZtD9lxcIbLO5produjnqtyZgpidfvu3NqrvtZFqBwPFrLYzAZR+Kt+4wlo3twpBVVeiEr3Ee155u9Y/KckYI2iBo82jdgtslkTwXT2lIhIJ24nzvCOXiCDdcbQxjQM+VHqDWsRwy6MjHO41oX/ti8EZL+5TPYj+rcvlSec2gMOKucTpYZxzLMXagW19MolLdbjAlpO5jCeEcIr248jxKr+WhHnw/RD+A+1wH7bZ6Jc/Q9L/NXVb4VZowNiM2eSjqw==
  template:
    metadata:
      name: mcp-hr-server-db-secret
      namespace: ai-services
    type: Opaque
